control_field_max_length: false
exclude_chunk_from_metadata: false
indexing_options:
  url:
    indexing_option: contextual_content
    max: -1
  body:
    indexing_option: main_content
    max: -1
  localgov_directory_job_title:
    indexing_option: contextual_content
    max: -1
  localgov_directory_phone:
    indexing_option: contextual_content
    max: -1
  type:
    indexing_option: contextual_content
    max: -1
  localgov_directory_address:
    indexing_option: contextual_content
    max: -1
  title:
    indexing_option: contextual_content
    max: -1
